#!/usr/bin/env sh
MYSQL_PS1='#random-mysql> ' `node -e 'conf=require("../../pound-random-secret").database;console.log("mysql -h" + conf.host + " -u" + conf.user + " -p" + conf.password + " " + conf.database);'`
